### ISSUE TITLE
ExecutionControl::unsubscribe() comment disagreement with code

### ISSUE THREAD

**Issue by sochsner1** [nasa/TrickHLA#100]
https://github.com/nasa/TrickHLA/blob/af2df5edcf31b0d70ee3d6c559015eda1ad4914a/source/SpaceFOM/ExecutionControl.cpp#L477-L483

Lines 480 and 481 seem to contradict each other. I am reading the implementation to be: Unsubscribe from the execution configuration if we _ARE_ the Master federate.

Awesome project, thanks!

**Comment by dandexter** [comment]
Yes, this is a bug. The check needs to be for if this federate is not the master. Thank you for your bug report.

**Comment by dandexter** [comment]
Fixed and tested.
