### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [nasa/TrickHLA#101]
I would like to point out that identifiers like “[`_DSES_EXECUTON_CONTROL_HH_`](https://github.com/nasa/TrickHLA/blob/dd1827ea1a3ad570ae468726213b337f20fcfc82/include/DSES/ExecutionControl.hh#L35 "Update candidate")” and “[`_TRICKHLA_UTILITIES_HH_`](https://github.com/nasa/TrickHLA/blob/838a917a159f17d32bff57284d3631158fe6f5fc/include/TrickHLA/Utilities.hh#L37 "Another update candidate")” [do eventually not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by dandexter** [comment]
Thank you for your report. The code has been updated to resolve the reserved identifiers in the header guards.

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/nasa/TrickHLA/commit/db1986ef6965ed8e71e977d9ea313d9e6da35601 "Renaming of include guards").
