### ISSUE TITLE
Add WheelBot example

### ISSUE THREAD

**Issue by ezcrues** [nasa/TrickHLA#119]
@Andyj4586 added a distributed version of the Trick WheelBot simulation.  This code is now in the 'wheelbot' branch but needs some more cleanup before merging into the 'master' branch.

**Comment by simtheverse** [comment]
In the S_define it includes a "THLA_interface.sm" but I can't find this file in the repo. Is this something that gets generated?

https://github.com/nasa/TrickHLA/blob/02321657f9181a27406ee5281dbb08af6982a2d3/sims/SpaceFOM/SIM_wheelbot/S_define#L64C20-L64C20

**Comment by dandexter** [comment]
The "THLA_interface.sm" simulaiton module is located in the top level S_modules directory. The S_overrides.mk file in the SIM_wheelbot directory has a line to add the S_modules directory to the TRICK_SFLAGS (i.e. TRICK_SFLAGS += -I${TRICKHLA_HOME}/S_modules), which is how Trick can find this sim-module.

**Comment by simtheverse** [comment]
I see, thanks for pointing me there. I branched from master for my project and didn't realize that was just in wheelbot branch for now.

**Comment by dandexter** [comment]
The wheelbot code and simulation and been merged into develop branch.
