### ISSUE TITLE
Add ability to specify where SpaceFOM modules are

### ISSUE THREAD

**Issue by simtheverse** [nasa/TrickHLA#126]
Hello!

I am keeping my FOM modules in a higher level Federation folder and don't want to have each federate having its own copy of the FOM modules. It would be great if I could optionally specify where the SpaceFOM modules are when instantiating SpaceFOMFederateConfig in the input.py file, or perhaps adding a clear self.fom_modules method and then I can call self.add_FOM_module directly.

https://github.com/nasa/TrickHLA/blob/55a1d4de913b6d9756af23f06a5dba56f8df97b4/Modified_data/SpaceFOM/SpaceFOMFederateConfig.py#L58-L62

**Comment by ezcrues** [comment]
We should be able to do that.  I will look into options.  I'm thinking that we can add a path argument with the current default value to the instantiation parameter list.  We should also be able to create a function to call post instantiation and prior to initializations that will allow you to set the path to the directory where the SpaceFOM modules are stored.

Right now, we create symbolic link from FOMs/SpaceFOM in the sim directory to wherever the SpaceFOM FOM modules are stored.  I would recommend to NOT duplicate the SpaceFOM modules if you can avoid it.

**Comment by dandexter** [comment]
The FOM module paths can either be relative to the directory the simulation executable is running from or it can be full absolute paths to the FOM module file.

TrickHLA uses the FOM modules specified to create a STL vector that is then passed to the RTI_ambassador->createFederationExecution() function.

**Comment by ezcrues** [comment]
Yes, but for the SpaceFOM, we already set the path to the SpaceFOM modules.  We need to provide and option to override those.  Unfortunately, right now, they are set in the Python SpaceFOMFederateConfig initializer.  We can give an option to override that.

**Comment by dandexter** [comment]
Then I agree, that allowing the user to specify the home directory to the SpaceFOM modules to would be a good update to the input file Python scripts.

**Comment by simtheverse** [comment]
I do this as a work around after making the federate object in the input.py:
```python
federate.fom_modules = []
federate.add_FOM_module(os.getenv("HLA_FEDERATION_FILES_PATH") + '/FOMs/SpaceFOM/SISO_SpaceFOM_switches.xml' )
federate.add_FOM_module(os.getenv("HLA_FEDERATION_FILES_PATH") + '/FOMs/SpaceFOM/SISO_SpaceFOM_datatypes.xml' )
federate.add_FOM_module(os.getenv("HLA_FEDERATION_FILES_PATH") + '/FOMs/SpaceFOM/SISO_SpaceFOM_management.xml' )
federate.add_FOM_module(os.getenv("HLA_FEDERATION_FILES_PATH") + '/FOMs/SpaceFOM/SISO_SpaceFOM_environment.xml' )
federate.add_FOM_module(os.getenv("HLA_FEDERATION_FILES_PATH") + '/FOMs/SpaceFOM/SISO_SpaceFOM_entity.xml' )
```
I like the symbolic link approach.. tragically my org's gitlab instance doesn't follow the symlink when running CI jobs.

**Comment by ezcrues** [comment]
@simtheverse, I checked in a modified version of SpaceFOMFederateConfig.py.  It now takes an optional parameter to set the SpaceFOM FOM module directory path.  There is also a function that you can all to override the current SpaceFOM FOM module path with a new one.  It needs to be called prior to the federate initialize function.

I just realized that I forgot to check for initialize.  Stand by for another update. :-)

**Comment by ezcrues** [comment]
Done!

**Comment by simtheverse** [comment]
Thank you :)
