### ISSUE TITLE
Add Fluid Distributed Interface demonstration sim

### ISSUE THREAD

**Issue by jasonlharvey** [nasa/TrickHLA#150]
Per discussion with Zack, I'm going to submit a pull request to add a Fluid Distributed Interface demonstration sim.

**Comment by ezcrues** [comment]
Thanks @jasonlharvey !  We'll pull this into a feature branch to check out and then merge it into develop.

This should be another great example.

**Comment by ezcrues** [comment]
Done!  Everything should be checked in a good to go in the 'development' branch.  We'll merge into the 'master' branch in the near future.  We have some other outstanding issues in work.
