### ISSUE TITLE
Fix call to obsolete sleep() function.

### ISSUE THREAD

**Issue by dandexter** [nasa/TrickHLA#9]
The C sleep() function is obsolete and was flagged as a flawfinder hit and we need to use nanosleep() instead.

**Comment by dandexter** [comment]
From flawfinder:
(obsolete) usleep: This C routine is considered obsolete (as opposed to the shell command by the same name). The interaction of this function with SIGALRM and other timer functions such as sleep(), alarm(), setitimer(), and nanosleep() is unspecified (CWE-676). Use nanosleep(2) or setitimer(2) instead.

**Comment by ezcrues** [comment]
Closed.
