### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by ezcrues** [nasa/TrickHLA#98]
The current set of Python maintenance scripts and input files were all developed and tested with a Python 2.7 version.  Python 2.7 has been deprecated and is now no longer available on the Mac.  We need to migrate all these scripts and input files to Python 3.

**Comment by dandexter** [comment]
Updated the Python scripts to use Python 3 and pushed the changes.

**Comment by ezcrues** [comment]
This issue is now closed with Dan's commits.
