### ISSUE TITLE
Typo that may impact functionality

### ISSUE THREAD

**Issue by sochsner1** [nasa/TrickHLA#99]
https://github.com/nasa/TrickHLA/blob/af2df5edcf31b0d70ee3d6c559015eda1ad4914a/Modified_data/TrickHLA/TrickHLAFederateConfig.py#L67

There is a typo on the above line. The self.endabled property doesn't appear to be referenced again but self.enabled does later get referenced:
https://github.com/nasa/TrickHLA/blob/af2df5edcf31b0d70ee3d6c559015eda1ad4914a/Modified_data/TrickHLA/TrickHLAFederateConfig.py#L163-L165

The SpaceFOM example Sim_Roles_Test_Sync works for me and it inherits this class so I am not sure what functionality this impacts.

Awesome project. Thanks!

**Comment by dandexter** [comment]
Yes, the typo is a bug and will be fixed. Thank you for your bug report.

**Comment by dandexter** [comment]
This has been fixed and tested.
